---
- name: Extract grub.cfg
  command: "7z e {{ iso_path | default(base_path) }}/{{ iso }} -o{{ working_folder.path }}/EFI/BOOT EFI/BOOT/grub.cfg"
  changed_when: true
  delegate_to: "{{ builder_delegate }}"

- include_role:
    name: network_interfaces
    tasks_from: network-scripts.yml
    apply:
      delegate_to: "{{ builder_delegate }}"
  vars:
    dest_folder: "{{ working_folder.path }}/sysconfig"
    restart_network: no
  when: render_network | default('yes')

- name: Patch grub to enable autoinstall
  ansible.builtin.replace:
    path: "{{ working_folder.path }}/EFI/BOOT/grub.cfg"
    regexp: ' quiet'
    replace: ' inst.ks=cdrom:/kickstart/kickstart.cfg'
  delegate_to: "{{ builder_delegate }}"

- name: Decrease timeout in grub to 3 seconds
  ansible.builtin.replace:
    path: "{{ working_folder.path }}/EFI/BOOT/grub.cfg"
    regexp: '^.*set timeout.*$'
    replace: 'set timeout=3'
  delegate_to: "{{ builder_delegate }}"

- name: Set default to 0
  ansible.builtin.replace:
    path: "{{ working_folder.path }}/EFI/BOOT/grub.cfg"
    regexp: '^.*set default.*$'
    replace: 'set default="0"'
  delegate_to: "{{ builder_delegate }}"

# TODO: Copy packages to ISO

- name: "Generate kickstart file for rhel"
  template:
    src: rhel/kickstart.j2
    dest: "{{ working_folder.path }}/kickstart/kickstart.cfg"
    mode: u=rw,go=r
  delegate_to: "{{ builder_delegate }}"

- name: Patch iso with autoinstall and new files
  command: >
    xorriso -dev {{ base_path }}/iso/{{ virgil_hostname }}.iso
    -boot_image any replay
    -map {{ working_folder.path }}/kickstart kickstart
    -map {{ working_folder.path }}/drivers drivers
    -map {{ working_folder.path }}/sysconfig sysconfig
    -map {{ working_folder.path }}/EFI/BOOT/grub.cfg EFI/BOOT/grub.cfg
    -commit -eject all
  changed_when: true
  delegate_to: "{{ builder_delegate }}"
