---
- name: "Include {{ target_os }} specific variables file"
  include_vars: "main_{{ target_os | lower }}.yml"

- name: "Include {{ target_os }} specific tasks file"
  include_tasks: "package_bundle_{{ target_os | lower }}.yml"
